namespace RelatoriosRosset.Models
{
    public class GerarProdutoHistoricoModel
    {
        public string? PRODUTO { get; set; }
        public string? Mensagem { get; set; }
        public string? COR_PRODUTO { get; set; }
        public string? FILIAL { get; set; }
        public DateTime? DATA_SALDO { get; set; }
        public Boolean? SALDO_MOV_EXCLUIDO { get; set; }
        public Decimal? CUSTO_MEDIO1 { get; set; }
        public Decimal? CUSTO_MEDIO2 { get; set; }
        public Decimal? CUSTO_MEDIO3 { get; set; }
        public Decimal? CUSTO_MEDIO4 { get; set; }
        public Decimal? ULTIMO_CUSTO1 { get; set; }
        public Decimal? ULTIMO_CUSTO2 { get; set; }
        public Decimal? ULTIMO_CUSTO3 { get; set; }
        public Decimal? ULTIMO_CUSTO4 { get; set; }
        public DateTime? DATA_CUSTO_MEDIO { get; set; }
        public DateTime? DATA_ULT_CUSTO { get; set; }
        public DateTime? ULTIMA_SAIDA { get; set; }
        public DateTime? ULTIMA_ENTRADA { get; set; }
        public int? ESTOQUE { get; set; }
        public int? S1 { get; set; }
        public int? S2 { get; set; }
        public int? S3 { get; set; }
        public int? S4 { get; set; }
        public int? S5 { get; set; }
        public int? S6 { get; set; }
        public int? S7 { get; set; }
        public int? S8 { get; set; }
        public int? S9 { get; set; }
        public int? S10 { get; set; }
        public int? S11 { get; set; }
        public int? S12 { get; set; }
        public int? S13 { get; set; }
        public int? S14 { get; set; }
        public int? S15 { get; set; }
        public int? S16 { get; set; }
        public int? S17 { get; set; }
        public int? S18 { get; set; }
        public int? S19 { get; set; }
        public int? S20 { get; set; }
        public int? S21 { get; set; }
        public int? S22 { get; set; }
        public int? S23 { get; set; }
        public int? S24 { get; set; }
        public int? S25 { get; set; }
        public int? S26 { get; set; }
        public int? S27 { get; set; }
        public int? S28 { get; set; }
        public int? S29 { get; set; }
        public int? S30 { get; set; }
        public int? S31 { get; set; }
        public int? S32 { get; set; }
        public int? S33 { get; set; }
        public int? S34 { get; set; }
        public int? S35 { get; set; }
        public int? S36 { get; set; }
        public int? S37 { get; set; }
        public int? S38 { get; set; }
        public int? S39 { get; set; }
        public int? S40 { get; set; }
        public int? S41 { get; set; }
        public int? S42 { get; set; }
        public int? S43 { get; set; }
        public int? S44 { get; set; }
        public int? S45 { get; set; }
        public int? S46 { get; set; }
        public int? S47 { get; set; }
        public int? S48 { get; set; }
        public int? QTDE_ENTRADA { get; set; }
        public int? QTDE_FATURAMENTO { get; set; }
        public int? QTDE_ENT_DEVOL { get; set; }
        public int? QTDE_FATURA_DEVOL { get; set; }
        public int? QTDE_PROD_ENT { get; set; }
        public int? QTDE_PROD_SAI { get; set; }
        public int? QTDE_AJUSTE { get; set; }
        public int? QTDE_LJ_ENT { get; set; }
        public int? QTDE_LJ_SAI { get; set; }
        public int? QTDE_VENDA { get; set; }
        public int? QTDE_TROCA { get; set; }
        public DateTime? DATA_CUSTO_MEDIO_INIC { get; set; }
        public Decimal? CUSTO_MEDIO1_INIC { get; set; }
        public Decimal? CUSTO_MEDIO2_INIC { get; set; }
        public Decimal? CUSTO_MEDIO3_INIC { get; set; }
        public Decimal? CUSTO_MEDIO4_INIC { get; set; }
        public DateTime? GERACAO { get; set; }
        public Boolean? MATRIZ_FISCAL { get; set; }
        public DateTime? DATA_PARA_TRANSFERENCIA { get; set; }
    }
}
