namespace RelatoriosRosset.Models
{
    public class LojaNotaFiscalModel
    {
        public string CODIGO_FILIAL { get; set; }
        public string NF_NUMERO { get; set; }
        public string SERIE_NF { get; set; }
        public string? CODIGO_CLIENTE { get; set; }
        public string? CODIGO_FILIAL_DESTINO { get; set; }
        public string NATUREZA_OPERACAO_CODIGO { get; set; }
        public DateTime EMISSAO { get; set; }
        public DateTime? DATA_SAIDA { get; set; }
        public bool RECEBIMENTO { get; set; }
        public Decimal QTDE_TOTAL { get; set; }
        public Decimal PESO_LIQUIDO { get; set; }
        public Decimal PESO_BRUTO { get; set; }
        public int VOLUMES { get; set; }
        public string? TIPO_VOLUME { get; set; }
        public string? MARCA_VOLUME { get; set; }
        public Decimal FRETE { get; set; }
        public Decimal SEGURO { get; set; }
        public byte? FRETE_A_PAGAR { get; set; }
        public Decimal VALOR_TOTAL_ITENS { get; set; }
        public Decimal DESCONTO { get; set; }
        public Decimal ENCARGO { get; set; }
        public Decimal VALOR_TOTAL { get; set; }
        public string? OBS { get; set; }
        public bool NOTA_IMPRESSA { get; set; }
        public string? TRANSP_RAZAO_SOCIAL { get; set; }
        public string? TRANSP_UF { get; set; }
        public string? TRANSP_CIDADE { get; set; }
        public string? TRANSP_CGC { get; set; }
        public string? TRANSP_INSCRICAO { get; set; }
        public string? TRANSP_ENDERECO { get; set; }
        public bool INDICA_CONSUMIDOR_FINAL { get; set; }
        public Decimal VALOR_IMPOSTO_AGREGAR { get; set; }
        public int? CTB_LANCAMENTO { get; set; }
        public int? CTB_ITEM { get; set; }
        public int EMPRESA { get; set; }
        public string? COD_CLIFOR { get; set; }
        public bool NOTA_CANCELADA { get; set; }
        public DateTime? DATA_CANCELAMENTO { get; set; }
        public Decimal VALOR_CANCELADO { get; set; }
        public DateTime DATA_PARA_TRANSFERENCIA { get; set; }
        public Decimal QTDE_CANCELADA { get; set; }
        public byte? TIPO_ORIGEM { get; set; }
        public int? SEQUENCIAL_UNICO { get; set; }
        public DateTime? DATA_GERACAO_NSU { get; set; }
        public string? CHAVE_NFE { get; set; }
        public string? PROTOCOLO_AUTORIZACAO_NFE { get; set; }
        public DateTime? DATA_AUTORIZACAO_NFE { get; set; }
        public bool GERAR_AUTOMATICO { get; set; }
        public short STATUS_NFE { get; set; }
        public short LOG_STATUS_NFE { get; set; }
        public string? MOTIVO_CANCELAMENTO_NFE { get; set; }
        public bool PRIORIZACAO { get; set; }
        public byte? TIPO_EMISSAO_NFE { get; set; }
        public byte? FIN_EMISSAO_NFE { get; set; }
        public string? REGISTRO_DPEC { get; set; }
        public string? PIN { get; set; }
        public DateTime? DATA_REGISTRO_DPEC { get; set; }
        public string? PROTOCOLO_CANCELAMENTO_NFE { get; set; }
        public DateTime? DATA_CONTINGENCIA { get; set; }
        public string? JUSTIFICATIVA_CONTINGENCIA { get; set; }
        public string? OBS_INTERESSE_FISCO { get; set; }
        public bool? TRANSP_PF_PJ { get; set; }
        public string? NF_NUMERO_REFERENCIADA { get; set; }
        public string? SERIE_NF_REFERENCIADA { get; set; }
        public byte? LX_STATUS_NOTA_FISCAL { get; set; }
        public string? EMAIL_NFE { get; set; }
        public string? INFORMACAO_COMPLEMENTAR { get; set; }
        public DateTime? DATA_HORA_EMISSAO { get; set; }
        public DateTime? DATA_HORA_SAIDA { get; set; }
        public byte? INDICA_PRESENCA_COMPRADOR { get; set; }
        public string? TRANSPORTADORA { get; set; }
        public byte? UTC_DATA_SAIDA { get; set; }
        public byte? UTC_EMISSAO { get; set; }
        public byte? UTC_DATA_AUTORIZACAO_NFE { get; set; }
        public Decimal? VALOR_APROX_IMPOSTOS { get; set; }
        public string? ID_ENDERECO_ENTREGA { get; set; }
        public string? NUMERO_CONHECIMENTO_RELACIONADO { get; set; }
        public string? OBS_INTERESSE_FISCO_MS { get; set; }
        public int? ID_INTERMEDIADOR { get; set; }
        public bool? PGTO_INTERMEDIADOR { get; set; }
        public string? DESC_MEIO_PGTO { get; set; }
        public string? NOME_ENTREGA { get; set; }
        public string? URL_ENVIO { get; set; }
        public string? ID_PROCESSO { get; set; }
    }
}
